DROP DATABASE IF EXISTS r2pdb;
CREATE DATABASE r2pdb;
USE r2pdb;

DROP TABLE IF EXISTS countries;
CREATE TABLE countries
(
	CountryID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CountrySymbol VARCHAR(6) NOT NULL,
	CountryName VARCHAR(128) NOT NULL,
	FlagPath VARCHAR(128)
) ENGINE=INNODB;

DROP TABLE IF EXISTS genders;
CREATE TABLE genders
(
	GenderID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	GenderName VARCHAR(128) NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS publishers;
CREATE TABLE publishers
(
	PublisherID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PublisherName VARCHAR(128) NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS languages;
CREATE TABLE languages
(
	LanguageID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LanguageName VARCHAR(128) NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS genres;
CREATE TABLE genres
(
	GenreID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	GenreName VARCHAR(128) NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS users;
CREATE TABLE users
(
	UserID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LoginName VARCHAR(128) NOT NULL,
	Password VARCHAR(128) NOT NULL,
	RegistrationDate DATETIME NOT NULL,
	FirstName VARCHAR(128),
	LastName VARCHAR(128),
	Age INT UNSIGNED,
	GenderID TINYINT UNSIGNED,
	CountryID SMALLINT UNSIGNED,
	ScreenName VARCHAR(128) NOT NULL,
	AvatarPath VARCHAR(128),
	Bio TEXT,
	
	FOREIGN KEY (CountryID) REFERENCES countries(CountryID),
	FOREIGN KEY (GenderID) REFERENCES genders(GenderID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS comments;
CREATE TABLE comments
(
	CommentID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PostDate DATETIME NOT NULL,
	UserID INT UNSIGNED NOT NULL,
	Text TEXT NOT NULL,
	
	FOREIGN KEY (UserID) REFERENCES users(UserID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS userComments;
CREATE TABLE userComments
(
	UserID INT UNSIGNED NOT NULL,
	CommentID INT UNSIGNED NOT NULL,
	
	PRIMARY KEY (UserID, CommentID),
	FOREIGN KEY (UserID) REFERENCES users(UserID),
	FOREIGN KEY (CommentID) REFERENCES comments(CommentID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS products;
CREATE TABLE products
(
	ProductID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(512) NOT NULL,
	ReleaseDate date,
	ImagePath VARCHAR(128),
	LanguageID MEDIUMINT UNSIGNED,
	Brief VARCHAR(256),
	Description TEXT,
	EAN13 BIGINT(13) UNSIGNED ZEROFILL,
	PublisherID MEDIUMINT UNSIGNED,
	
	FOREIGN KEY (LanguageID) REFERENCES languages(LanguageID),
	FOREIGN KEY (PublisherID) REFERENCES publishers(PublisherID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS productComments;
CREATE TABLE productComments
(
	ProductID INT UNSIGNED NOT NULL,
	CommentID INT UNSIGNED NOT NULL,
	
	PRIMARY KEY (ProductID, CommentID),
	FOREIGN KEY (ProductID) REFERENCES products(ProductID),
	FOREIGN KEY (CommentID) REFERENCES comments(CommentID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS productGenres;
CREATE TABLE productGenres
(
	ProductID INT UNSIGNED NOT NULL,
	GenreID MEDIUMINT UNSIGNED NOT NULL,
	
	PRIMARY KEY (ProductID, GenreID),
	FOREIGN KEY (ProductID) REFERENCES products(ProductID),
	FOREIGN KEY (GenreID) REFERENCES genres(GenreID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS reviews;
CREATE TABLE reviews
(
	ReviewID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ReviewDate DATETIME NOT NULL,
	ProductID INT UNSIGNED NOT NULL,
	UserID INT UNSIGNED NOT NULL,
	Text TEXT NOT NULL,
	Pros TEXT,
	Cons TEXT,
	Rating TINYINT NOT NULL,
	
	FOREIGN KEY (ProductID) REFERENCES products(ProductID),
	FOREIGN KEY (UserID) REFERENCES users(UserID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS reviewComments;
CREATE TABLE reviewComments
(
	ReviewID INT UNSIGNED NOT NULL,
	CommentID INT UNSIGNED NOT NULL,
	
	PRIMARY KEY (ReviewID, CommentID),
	FOREIGN KEY (ReviewID) REFERENCES reviews(ReviewID),
	FOREIGN KEY (CommentID) REFERENCES comments(CommentID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS collections;
CREATE TABLE collections
(
	CollectionID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CollectionName VARCHAR(128) NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS userCollections;
CREATE TABLE userCollections
(
	UserID INT UNSIGNED NOT NULL,
	CollectionID INT UNSIGNED NOT NULL,
	
	PRIMARY KEY (UserID, CollectionID),
	FOREIGN KEY (UserID) REFERENCES users(UserID),
	FOREIGN KEY (CollectionID) REFERENCES collections(CollectionID)
) ENGINE=INNODB;

DROP TABLE IF EXISTS collectionProducts;
CREATE TABLE collectionProducts
(
	CollectionID INT UNSIGNED NOT NULL,
	ProductID INT UNSIGNED NOT NULL,
	
	PRIMARY KEY (CollectionID, ProductID),
	FOREIGN KEY (CollectionID) REFERENCES collections(CollectionID),
	FOREIGN KEY (ProductID) REFERENCES products(ProductID)
) ENGINE=INNODB;